---
title: "Giovanni Colitti's resume"
author: Giovanni Colitti
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    standalone: true
    embed-resources: true
    css: ['resume.css']
    align: left
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

```{css, echo = FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> g.a.colitti@gmail.com
- <i class="fa fa-github"></i> [github.com/gacolitti](https://github.com/gacolitti)
- <i class="fa fa-linkedin"></i> [https://tinyurl.com/yfrrpukt](https://www.linkedin.com/in/giovanni-colitti-17821b6b/)
- <i class="fab fa-stack-overflow"></i> [https://tinyurl.com/twxsa92](https://stackoverflow.com/users/9489566/giovanni-colitti?tab=profile)
- <i class="fab fa-blogger-b"></i> [giovannicolitti.com](https://giovannicolitti.com)

Skills {#skills}
--------------------------------------------------------------------------------

- **Analytical Methods**: 
regression, classification, clustering, feature engineering, linear
programming and optimization methods, causal analysis, Bayesian and Monte
Carlo methods

- **Programming**: 
R (including dplyr, data.table, shiny, echarts4r, ompr, tidymodels), 
SQL (MySQL, PostgreSQL, GoogleSQL, MSSQL), Bash, Python, Stata, Javascript/HTML/CSS

- **Tools**: 
Git, Docker, Google Cloud Platform, BigQuery, Visual Studio Code, RStudio

- **Languages**:
Fluent in English and Chinese

- **Bonus**:



Main
================================================================================

Giovanni Colitti {#title}
--------------------------------------------------------------------------------

Experienced Data Scientist with a strong background in Economics, currently building tools to 
drive insights and visibility into cloud infrastructure at Apple. 


Experience {data-icon=suitcase}
--------------------------------------------------------------------------------


### Apple (contract)

*Data Scientist*

Remote

2022 - Current

- Led the optimization of BigQuery table schemas and pipelines for trillions of rows of data, 
  reducing query costs by over 90%.
- Contributed to the development of a K8s cost model, wrote an API 
  to facilitate the extraction of cost information from the model, and designed a Shiny app for 
  visualization and counterfactual analysis.
- Automated tooling for customer chargebacks and built tools to forecast resource 
  clawbacks, streamlining reporting and planning processes.
- Developed and presented interactive K8s usage reports, enhancing internal customer 
  visibility and efficiency.
- Performed simulations to quantify the impact of new server configs on resource fragmentation and cost.

  
### Fieldin

*Senior Business Intelligence Analyst*

Remote

2020 - 2022

- Developed an app for interactive drag-and-drop creation of visualizations and tables in PowerPoint slides, 
  saving users hours per week as revealed by a user survey.
- Created an algorithm for counting harvest loads by analyzing distance patterns, achieving 90% 
  prediction accuracy.
- Developed an app for interactive mapping of machine data and additional apps for ad-hoc 
  report creation, supporting the customer success team.
- Managed database tables serving as the backend for the apps used to support the customer success team.
- Created and managed a platform for developing and publishing web applications using ShinyProxy.

### Grimmway

*Data Scientist*

Remote

2018 - 2020

- Developed machine learning models to improve sales and yield forecasts by 30-50% over previous 
  methods.
- Built a YOLO v5 object detection pipeline to generate carrot stand count estimates with 95% 
  accuracy, dramatically decreasing costs.
- Developed LP models to optimize planting and harvesting, maximizing yield and 
  meeting sales demand.
- Developed an R package for time-series cross-validation.
- Analyzed research trial data, performed sample size calculations, and provided spatial sampling 
  recommendations to the agronomy team.
  
Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### National Taiwan University

M.S. in Agricultural Economics (4.0 GPA)

Taipei, Taiwan

2018

### California State University, Channel Islands 

B.A. in Economics (3.8 GPA)

Camarillo, CA

2016


\pagebreak

Selected Research {data-icon=file}
--------------------------------------------------------------------------------

### Do Concealed Firearms Decrease Crime? An Analysis Using Active Concealed Firearm License Data in the United States

Used a unique dataset on county-level concealed firearms permits and applied 
two-stage least squares estimation to show that concealed firearms do not decrease crime.

N/A

2018

DOI: http://dx.doi.org/10.6342/NTU201800993

### Do HEVs Cause More Cyclist & Pedestrian Injuries?

Used logit model & large UK accident-level dataset to show that quieter electric vehicles 
significantly increase pedestrian accidents net of other covariates including speed limit and 
urbanization. Also used Bayesian methods (MCMC) to estimate the posterior distribution and 
check for non-normality in estimates.

N/A

2018

### Effect of Hurricane Morakot on Agricultural Prices in Taiwan

Used a difference-in-differences (DiD) event study model and a large transaction-level dataset 
to quantify the casual effect of Hurricane Morakot on vegetable prices in Taiwan, adding weight 
to the literature that claims weather is oftentimes the most important driver of local agricultural 
prices.

N/A

2018

Academic Honors and Awards {data-icon=trophy}
--------------------------------------------------------------------------------

### Thesis Competition First Place Prize

Master’s thesis presentation competition first place winner.

N/A

2018

### Taiwan Ministry of Education Scholarship

Merit scholarship for post-graduate studies in Taiwan.

N/A

2016

### Program Honors in Economics

Selected by CSUCI Economics Department faculty for outstanding achievement.

N/A

2016

### Wang Family Scholarship

Merit scholarship for international study in Taiwan & Mainland China.

N/A

2014

### President's Scholarship

Highest scholastic achievement award in CSU system; only handful awarded annually. 

N/A

2012


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Last updated on `r Sys.Date()`.